/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.views.khachHang;

import com.nhom3.controller.ExportFileExcel;
import com.nhom3.entity.KhachHang;
import com.nhom3.service.HoaDonService;
import com.nhom3.service.KhachHangService;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.*;
import java.io.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author Hoang Viet
 */
public class khachHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form khachHangJPanel
     */
    DefaultTableModel defaultTableModel;
    KhachHangService khachHangService;
    ArrayList<KhachHang> khachHangs;
    JLabel label;
    KhachHang khachHang;
    FileNameExtensionFilter fileNameExtensionFilter;
    ExportFileExcel exportFileExcel;
    public khachHangJPanel() {
        initComponents();

        //add column for table
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        khachHangTable.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã khách hàng");
        defaultTableModel.addColumn("Họ tên");
        defaultTableModel.addColumn("Số điện thoại");
        defaultTableModel.addColumn("Địa Chỉ");

        khachHangService = new KhachHangService();
        setData(khachHangService.getAllKhachHang());
    }

    private void setData(ArrayList<KhachHang> khachHangs) {
        for (KhachHang khachHang : khachHangs) {
            defaultTableModel.addRow(new Object[]{khachHang.getMaKH(), khachHang.getHoTen(),
                khachHang.getSoDT(), khachHang.getDiaChi()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updateBookButton = new javax.swing.JButton();
        refeshButton = new javax.swing.JButton();
        addBookbutton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        khachHangTable = new javax.swing.JTable();
        timKiemComboBox = new javax.swing.JComboBox<>();
        timKiemTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        exportFileButton = new javax.swing.JButton();
        fileNameTextField = new javax.swing.JTextField();

        updateBookButton.setBackground(new java.awt.Color(0, 153, 0));
        updateBookButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        updateBookButton.setForeground(new java.awt.Color(255, 255, 255));
        updateBookButton.setText("Sửa Sách");
        updateBookButton.setBorderPainted(false);
        updateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookButtonActionPerformed(evt);
            }
        });

        refeshButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        refeshButton.setText("Refesh");
        refeshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshButtonActionPerformed(evt);
            }
        });

        addBookbutton.setBackground(new java.awt.Color(0, 153, 0));
        addBookbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addBookbutton.setForeground(new java.awt.Color(255, 255, 255));
        addBookbutton.setText("Thêm Khách hàng");
        addBookbutton.setBorderPainted(false);
        addBookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookbuttonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(153, 0, 0));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refeshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refeshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        khachHangTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        khachHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(khachHangTable);

        timKiemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại" }));

        timKiemTextField.setText("Nhập từ khóa tìm kiếm.");
        timKiemTextField.setToolTipText("");

        searchButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        searchButton.setText("Tìm Kiếm");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        exportFileButton.setBackground(new java.awt.Color(51, 0, 153));
        exportFileButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exportFileButton.setForeground(new java.awt.Color(255, 255, 255));
        exportFileButton.setText("Xuất File");
        exportFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportFileButtonActionPerformed(evt);
            }
        });

        fileNameTextField.setText("Tên File");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(timKiemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timKiemTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exportFileButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(timKiemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(timKiemTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exportFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(fileNameTextField)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookButtonActionPerformed
        int row = khachHangTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(khachHangJPanel.this, "Vui lòng chọn khách hàng trước!","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int maKH = Integer.valueOf(String.valueOf(khachHangTable.getValueAt(row, 0)));
            new UpdateKhachHangJFrame(maKH).setVisible(true);
        }
    }//GEN-LAST:event_updateBookButtonActionPerformed

    private void refeshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshButtonActionPerformed
        defaultTableModel.setRowCount(0);
        khachHangService = new KhachHangService();
        setData(khachHangService.getAllKhachHang());
    }//GEN-LAST:event_refeshButtonActionPerformed

    private void addBookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookbuttonActionPerformed
        new AddKhachHangJFrame().setVisible(true);
    }//GEN-LAST:event_addBookbuttonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int row = khachHangTable.getSelectedRow();

        int confirm = JOptionPane.showConfirmDialog(khachHangJPanel.this, "Bạn có chắc chắn muốn xóa không?");

        if (confirm == JOptionPane.YES_OPTION) {
            int maKH = Integer.valueOf(String.valueOf(khachHangTable.getValueAt(row, 0)));
            khachHangService.deleteKhachHang(maKH);
            JOptionPane.showMessageDialog(null, "Đã xóa!");

            defaultTableModel.setRowCount(0);
            khachHangService = new KhachHangService();
            setData(khachHangService.getAllKhachHang());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        khachHangService = new KhachHangService();
        switch (String.valueOf(timKiemComboBox.getSelectedItem())) {
            case "Mã khách hàng":
                khachHangs = khachHangService.searchKhachHang("MaKH", String.valueOf(timKiemTextField.getText()));
                if (khachHangs.size() == 0) {
                    label = new JLabel("Không tìm thấy kết quả");
                    label.setFont(new Font("Tahoma", Font.PLAIN, 18));
                    JOptionPane.showMessageDialog(khachHangJPanel.this, label, "Error", JOptionPane.ERROR_MESSAGE);
                    defaultTableModel.setRowCount(0);
                } else {
                    defaultTableModel.setRowCount(0);

                    setData(khachHangs);
                }
                break;
            case "Tên khách hàng":
                khachHangs = khachHangService.searchKhachHang("HoTen", String.valueOf(timKiemTextField.getText()));
                if (khachHangs.size() == 0) {
                    label = new JLabel("Không tìm thấy kết quả");
                    label.setFont(new Font("Tahoma", Font.PLAIN, 18));
                    JOptionPane.showMessageDialog(khachHangJPanel.this, label, "Error", JOptionPane.ERROR_MESSAGE);
                    defaultTableModel.setRowCount(0);
                } else {
                    defaultTableModel.setRowCount(0);

                    setData(khachHangs);
                }
                break;
            case "Địa chỉ":
                khachHangs = khachHangService.searchKhachHang("DiaChi", String.valueOf(timKiemTextField.getText()));
                if (khachHangs.size() == 0) {
                    label = new JLabel("Không tìm thấy kết quả");
                    label.setFont(new Font("Tahoma", Font.PLAIN, 18));
                    JOptionPane.showMessageDialog(khachHangJPanel.this, label, "Error", JOptionPane.ERROR_MESSAGE);
                    defaultTableModel.setRowCount(0);
                } else {
                    defaultTableModel.setRowCount(0);

                    setData(khachHangs);
                }
                break;
            case "Số điện thoại":
                khachHangs = khachHangService.searchKhachHang("SoDT", String.valueOf(timKiemTextField.getText()));
                if (khachHangs.size() == 0) {
                    label = new JLabel("Không tìm thấy kết quả");
                    label.setFont(new Font("Tahoma", Font.PLAIN, 18));
                    JOptionPane.showMessageDialog(khachHangJPanel.this, label, "Error", JOptionPane.ERROR_MESSAGE);
                    defaultTableModel.setRowCount(0);
                } else {
                    defaultTableModel.setRowCount(0);

                    setData(khachHangs);
                }
                break;
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void exportFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportFileButtonActionPerformed
        exportFileExcel = new ExportFileExcel();
        StringBuffer path = new StringBuffer();
        path.append("C:\\Users\\Admin\\Desktop\\");
            path.append(fileNameTextField.getText());
            path.append(".xlsx");
            String path2 = path.toString();

            try {
                exportFileExcel.writeToExcell(khachHangTable,path2);
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Lưu file không thành công!");
            }
    }//GEN-LAST:event_exportFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookbutton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exportFileButton;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable khachHangTable;
    private javax.swing.JButton refeshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> timKiemComboBox;
    private javax.swing.JTextField timKiemTextField;
    private javax.swing.JButton updateBookButton;
    // End of variables declaration//GEN-END:variables
}
